### PR TITLE
Make vcm compatible with py37

### LINKED ISSUE #1853: vcm doesn't work with python 3.7
Google colab is still on python 3.7, but vcm has some dependencies that aren't. It would be nice to support 3.7 for now to allow using vcm in more context. This is what I see when trying to use vcm from google colab.

```
      1 import dataclasses
      2 from toolz.functoolz import curry
----> 3 from typing import Callable, Literal, MutableMapping, Sequence, Set
      4 import xarray as xr
      5 import vcm

ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

Steps to reproduce the problem:
```
conda create -n py37 python=3.7 pip
conda run -n py37 pip install external/vcm
pip install external/vcm
python -c 'import vcm'
```

Potential solution: use `Literal` from typing_extensions rather than `typing`.

cc @mcgibbon

### PR DESCRIPTION
**Pull request by nbren12**
Some slight adjustments to make vcm usable from google colab.

Here is a working example: https://colab.research.google.com/drive/1jLCfdUy667UQxJHfeTXhp1NmPJzumHN2?usp=sharing

Resolves #1853

I tried adding some testing infrastructure for python 3.7, but couldn't get it to work right away. We can add it later if we start using python3.7 environments more often.

### CODE REVIEW

File: external/vcm/setup.py [hunk 1]
```diff
@@ -24,11 +24,12 @@
     "xgcm",
     "cftime",
     "pytest",
-    "google-cloud-storage>=1.28.0",
+    "google-cloud-storage>=1.18.1",
```
Comment (mcgibbon) [inline external/vcm/setup.py:27]: Do you need to re-make the constraints.txt?

Comment (nbren12) [reply external/vcm/setup.py:27]: No. The new version range contain the old one. so any lock file satisfying the old will also satisfy the new.

**Review by mcgibbon — APPROVED** [review]
LGTM, thanks!
