### ISSUE TITLE
vcm doesn't work with python 3.7

### ISSUE THREAD

**Issue by nbren12** [ai2cm/fv3net#1853]
Google colab is still on python 3.7, but vcm has some dependencies that aren't. It would be nice to support 3.7 for now to allow using vcm in more context. This is what I see when trying to use vcm from google colab.

```
      1 import dataclasses
      2 from toolz.functoolz import curry
----> 3 from typing import Callable, Literal, MutableMapping, Sequence, Set
      4 import xarray as xr
      5 import vcm

ImportError: cannot import name 'Literal' from 'typing' (/usr/lib/python3.7/typing.py)
```

Steps to reproduce the problem:
```
conda create -n py37 python=3.7 pip
conda run -n py37 pip install external/vcm
pip install external/vcm
python -c 'import vcm'
```

Potential solution: use `Literal` from typing_extensions rather than `typing`.

cc @mcgibbon

**Comment by mcgibbon** [comment]
Is using this workaround to [run Python 3.8 in google collab](https://localcoder.org/install-python-3-8-kernel-in-google-colaboratory) a workable solution?

```
!pip install kora
import kora.install.py38
```
